### ISSUE TITLE
你好，你这个项目能正常调用吗,我运行起来后consumer找到不到服务提供方

### ISSUE THREAD

**Issue by skiof007** [SoftwareKing/sc-gateway#1]
http://localhost:9000/SC-CONSUMER/hello/xujin请求报错如下:

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Aug 02 17:24:55 CST 2018
There was an unexpected error (type=Internal Server Error, status=500).
com.netflix.client.ClientException: Load balancer does not have available server for client: producer

**Comment by SoftwareKing** [comment]
@skiof007 服务提供者，启动了吗？可以加我微信Software_King交流
